# Generated by Django 2.1.5 on 2019-11-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building', models.CharField(default='', max_length=25)),
                ('RoomNo', models.CharField(default='', max_length=5)),
                ('Capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstID', models.CharField(default='', max_length=5)),
                ('InstName', models.TextField(default='')),
                ('DeptName', models.TextField(default='')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
