# Generated by Django 2.1.5 on 2019-11-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20191110_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='InstID',
        ),
        migrations.AddField(
            model_name='project',
            name='Instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.Instructor'),
        ),
    ]
