# Generated by Django 2.1.5 on 2019-11-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20191111_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Feedback',
        ),
    ]
