# Generated by Django 2.1.5 on 2019-11-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Cpi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='DepName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
