# Generated by Django 2.1.5 on 2019-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191116_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takescourse',
            name='Feedback',
        ),
        migrations.AddField(
            model_name='takescourse',
            name='FeedbackGiven',
            field=models.BooleanField(default='0'),
        ),
    ]
