# Generated by Django 2.1.5 on 2019-11-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191116_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='takescourse',
            name='CourseID',
            field=models.CharField(default='', max_length=5),
        ),
    ]
