# Generated by Django 2.1.5 on 2019-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_takescourse_feedbackgiven'),
    ]

    operations = [
        migrations.AddField(
            model_name='takescourse',
            name='CourseID',
            field=models.CharField(default='', max_length=5),
        ),
    ]
