# Generated by Django 2.1.5 on 2019-11-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_takescourse_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='takescourse',
            name='FeedbackGiven',
            field=models.IntegerField(default=0),
        ),
    ]
