# Generated by Django 2.1.5 on 2019-11-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_takescourse_feedbackgiven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takesproject',
            name='Feedback',
        ),
        migrations.AlterField(
            model_name='takescourse',
            name='FeedbackGiven',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
