# Generated by Django 2.1.5 on 2019-11-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_prereqs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prereqs',
        ),
    ]
